language: node_js

sudo: false

cache: 
  apt: true
  directories:
    - node_modules

node_js: stable

install: 
  - npm install -D
  - cd ./builder-webpack
  - npm install -D
  - cd ./test/smoke/template
  - npm install -D

scripts:
  - cd ./builder-webpack
  - npm test:istanbul